blank_issues_enabled: false
contact_links:
  - name: game request statuses
    url: https://docs.google.com/spreadsheets/d/1lGe5X9H3ry6xWvXKvHVghE3B0g8xK8Tb6sgAK7qiy0g/edit?gid=1126640825#gid=1126640825
    about: |
      check the status of your game request :P